version: "3.7"
services:
  app:
    restart: "no"
    environment:
      - TEST=true
      - DB_URL=mongodb://mongo:27017/consents-test_db
    command: npm test
  mongo:
    ports:
      - "27017:27017"
